concurrent = 8
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<description of runner>"
  url = "<gitlab URL here>"
  token = "<token>"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]